import { promises as fs } from 'node:fs'
import path from 'node:path'

/**
 * Reads translated copy for the llms.txt indexes at build time.
 *
 * Two sources, merged into one dotted-key lookup:
 *   locales/<code>/common.json   page titles, under `meta.*`
 *   locales/<code>/llms.json     llms.txt copy, exposed under `llms.*`
 *
 * The split matters: `common.json` is GENERATED by `i18next-cli extract`, which prunes
 * every key not reachable from a static `t()` call in components/hooks/layouts/lib/pages.
 * llms.txt copy has no such call site, so keeping it in `common.json` means the next
 * `pnpm validate` silently deletes it. Its own namespace file is untouched by the
 * extractor while still living in `locales/<code>/`, so it stays per-locale and
 * reviewable by the usual translation workflow.
 *
 * The generators run inside the Vite config bundle, outside React, so `react-i18next`
 * is unavailable; reading the JSON directly is the equivalent seam. Reading rather than
 * importing also keeps ~200 KB of JSON out of the config bundle.
 */

export type Strings = Record<string, string>

/** Flattens nested JSON into dotted keys, keeping string leaves only. */
export function flatten(value: unknown, prefix = '', out: Strings = {}): Strings {
  if (typeof value === 'string') {
    if (prefix) out[prefix] = value
    return out
  }
  if (Array.isArray(value)) {
    value.forEach((item, i) => flatten(item, prefix ? `${prefix}.${i}` : String(i), out))
    return out
  }
  if (value && typeof value === 'object') {
    for (const [key, child] of Object.entries(value)) flatten(child, prefix ? `${prefix}.${key}` : key, out)
  }
  return out
}

export const LLMS_NAMESPACE = 'llms'

async function readJson(root: string, locale: string, namespace: string): Promise<unknown> {
  const raw = await fs.readFile(path.join(root, 'locales', locale, `${namespace}.json`), 'utf8').catch(() => null)
  if (!raw) return null
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

/** `meta.*` from common.json plus the llms namespace re-prefixed as `llms.*`. */
async function readLocale(root: string, locale: string): Promise<Strings> {
  const [common, llms] = await Promise.all([readJson(root, locale, 'common'), readJson(root, locale, LLMS_NAMESPACE)])
  return { ...flatten(common), ...flatten(llms, LLMS_NAMESPACE) }
}

/** The merged `meta.*` + `llms.*` keys for one locale, with NO fallback. Used by tests. */
export async function loadRawStrings(root: string, locale: string): Promise<Strings> {
  return readLocale(root, locale)
}

/**
 * A lookup for `locale`, falling back to `fallbackLocale` per key (not per file), so
 * a partially translated locale still renders complete output.
 */
export async function loadStrings(root: string, locale: string, fallbackLocale = 'en') {
  const [primary, fallback] = await Promise.all([
    readLocale(root, locale),
    locale === fallbackLocale ? Promise.resolve({} as Strings) : readLocale(root, fallbackLocale),
  ])
  return (key: string): string => {
    const value = primary[key]
    if (typeof value === 'string' && value.trim()) return value
    return fallback[key] ?? ''
  }
}

export type Lookup = Awaited<ReturnType<typeof loadStrings>>

/** Route slugs are kebab-case; i18n keys are snake_case. Mirrors lib/seo-head.tsx. */
export const snake = (slug: string) => slug.replace(/-/g, '_')

/** `meta.solutions.companies_agm` from ('solutions', 'companies-agm'). */
export const metaKeyForSlug = (namespace: string, slug: string) => `meta.${namespace}.${snake(slug)}`

/** Meta titles carry a brand suffix that is noise inside an index that is already titled "Vocdoni". */
export { stripBrandSuffix } from '../brand'

/** First sentence of a docs `lead`, used as its one-line note so docs notes never need translating. */
export function firstSentence(text: string, max = 200): string {
  const trimmed = text.replace(/\s+/g, ' ').trim()
  if (!trimmed) return ''
  const match = /^(.+?[.!?])(\s|$)/.exec(trimmed)
  const sentence = match ? match[1] : trimmed
  return sentence.length > max ? `${sentence.slice(0, max - 1).trimEnd()}…` : sentence
}
