import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import {
  DEVELOPERS_API_BASE_URL,
  DEVELOPERS_SKILLS_URL,
  DEVELOPERS_STATUS_URL,
  DEVELOPERS_SWAGGER_URL,
} from '../lib/developers'

/**
 * Emits the ARD (Agentic Resource Discovery) capability manifest so registries can index
 * what this origin offers to agents *before* invoking anything.
 *
 * Spec: ARD v0.91 (github.com/ards-project/ard-spec), schema
 * `spec/schemas/ai-catalog.schema.json` ("AICatalogManifest").
 *
 * Files emitted (all under `dist/client`):
 *   /.well-known/ard.json          canonical ARD path (spec section 5.1)
 *   /.well-known/ai-catalog.json   predecessor path, same bytes
 *
 * WHY BOTH PATHS: ARD section 5.1 makes `/.well-known/ard.json` the one path a conformant
 * consumer MUST fetch, and demotes `/.well-known/ai-catalog.json` to a predecessor that
 * consumers MAY consult - "a publisher on the predecessor path SHOULD move to ard.json".
 * Publishing only the predecessor risks not being found at all. But the older path is what
 * already-deployed crawlers look for, and one document satisfies both schemas at once:
 * `AICatalogManifest` requires `specVersion` + `entries`, and `ArdManifest` requires only
 * `entries` while leaving other top-level members open. So we serve identical bytes at both
 * and stay conformant either way, at the cost of one extra small file.
 *
 * Everything is derived at build time from `lib/developers.ts` and the `hostname` option
 * (CI passes a per-deploy SITE_URL, so preview deploys advertise themselves, not vocdoni.io),
 * which is the same anti-drift rule `plugins/well-known.ts` follows.
 *
 * NOTE: the `Content-Type: application/json` and `Access-Control-Allow-Origin: *` headers
 * these files need on Netlify come from `_headers`, which is generated by
 * `plugins/well-known.ts`. The dev middleware below sets them directly.
 */

interface Options {
  hostname: string
  /** Locale used for the raw-markdown docs URL, which is emitted per locale by plugins/docs-markdown.ts. */
  defaultLocale: string
}

const stripSlash = (s: string) => s.replace(/\/+$/, '')

/**
 * Only "1.0" is accepted by the manifest schema's `specVersion` enum.
 */
export const AI_CATALOG_SPEC_VERSION = '1.0'

/**
 * The `<publisher>` segment of every `urn:air:` identifier. Deliberately hardcoded rather
 * than derived from `hostname`, for three reasons the spec is explicit about:
 *
 *  1. A URN is *identity*, not location. The naming guide (Scenario C) says an owner of a
 *     real FQDN must use it "even when developing and running locally", so "the URN remains
 *     completely identical between their local development, staging, and production
 *     catalogs". Deriving it from SITE_URL would mint a different identity for the same
 *     logical resource on every preview deploy, breaking the stable primary key registries
 *     index on. The per-deploy host still varies - it belongs in `url`, which is location.
 *  2. The `<publisher>` segment is the authority anchor: registries extract it and
 *     cross-reference it against DNS/DID attestations. Only vocdoni.io is verifiable.
 *  3. The identifier pattern (`^urn:air:[a-zA-Z0-9.-]+(:[a-zA-Z0-9._-]+)+$`) has no room for
 *     a port, so a `http://localhost:3000` dev hostname could not produce a valid URN, and
 *     the naming guide names `localhost` an outright anti-pattern.
 */
export const URN_PUBLISHER = 'vocdoni.io'

const urn = (namespace: string, name: string) => `urn:air:${URN_PUBLISHER}:${namespace}:${name}`

// --- pure builders (unit-tested) --------------------------------------------

export interface CatalogEntry {
  identifier: string
  displayName: string
  /** IANA media type of the artifact at `url`. */
  type: string
  url: string
  description: string
  tags: string[]
  /** Registries build their semantic index from these; the schema caps the array at 2-5. */
  representativeQueries: string[]
}

export interface AiCatalogManifest {
  specVersion: string
  host: {
    displayName: string
    documentationUrl: string
    logoUrl: string
  }
  entries: CatalogEntry[]
}

/**
 * Builds the manifest document. Every entry points at something that actually exists and
 * resolves - either a constant from `lib/developers.ts` or a path this build emits.
 *
 * `host.identifier` and `trustManifest` are intentionally omitted: both are optional, and
 * both would assert a verifiable identity (a `did:web:vocdoni.io` document, an attestation)
 * that this origin does not currently serve. Advertising an identity that does not resolve
 * is worse than advertising none.
 */
export function buildAiCatalogDocument(hostname: string, defaultLocale: string): AiCatalogManifest {
  const host = stripSlash(hostname)

  return {
    specVersion: AI_CATALOG_SPEC_VERSION,
    host: {
      displayName: 'Vocdoni',
      documentationUrl: `${host}/developers`,
      logoUrl: `${host}/images/vocdoni_logotype_full_blank.svg`,
    },
    entries: [
      {
        identifier: urn('api', 'openapi'),
        displayName: 'Vocdoni API OpenAPI specification',
        type: 'application/yaml',
        url: DEVELOPERS_SWAGGER_URL,
        description:
          'Machine-readable OpenAPI description of the Vocdoni SaaS API: every endpoint, request body and response schema for creating organizations, censuses, voting processes and votes.',
        tags: ['api', 'openapi', 'voting'],
        representativeQueries: [
          'how do I create an election with the Vocdoni API',
          'what request body does the Vocdoni census endpoint expect',
          'which endpoints does the Vocdoni API expose',
          'how do I authenticate against the Vocdoni API',
        ],
      },
      {
        identifier: urn('api', 'rest'),
        displayName: 'Vocdoni API',
        type: 'application/json',
        url: DEVELOPERS_API_BASE_URL,
        description:
          'Base URL of the Vocdoni SaaS REST API, the single endpoint integrators call to run verifiable elections without touching the underlying protocol.',
        tags: ['api', 'rest', 'voting'],
        representativeQueries: [
          'what is the base URL of the Vocdoni API',
          'where do I send requests to create a Vocdoni voting process',
          'which host serves the Vocdoni REST API',
        ],
      },
      {
        identifier: urn('discovery', 'api-catalog'),
        displayName: 'Vocdoni API catalog',
        type: 'application/linkset+json',
        url: `${host}/.well-known/api-catalog`,
        description:
          'RFC 9727 API catalog for this origin, linking the Vocdoni API to its OpenAPI description, its human documentation and its status endpoint as an RFC 9264 linkset.',
        tags: ['discovery', 'api-catalog', 'rfc9727'],
        representativeQueries: [
          'where is the machine readable description of the Vocdoni API',
          'does Vocdoni publish an RFC 9727 API catalog',
          'what service documentation and status endpoints does Vocdoni expose',
        ],
      },
      {
        identifier: urn('discovery', 'llms-txt'),
        displayName: 'Vocdoni llms.txt index',
        type: 'text/plain',
        url: `${host}/llms.txt`,
        description:
          'llmstxt.org index of this site, listing the markdown versions of every developer documentation page and blog post for language models to read directly.',
        tags: ['discovery', 'llms-txt', 'documentation'],
        representativeQueries: [
          'what documentation does Vocdoni publish for language models',
          'give me an index of Vocdoni pages in markdown',
          'where is the llms.txt file for Vocdoni',
        ],
      },
      {
        identifier: urn('skills', 'index'),
        displayName: 'Vocdoni agent skills index',
        type: 'application/json',
        url: `${host}/.well-known/agent-skills/index.json`,
        description: `Agent Skills Discovery index of the skills Vocdoni publishes for coding agents, aggregated from ${DEVELOPERS_SKILLS_URL}.`,
        tags: ['agent-skills', 'discovery', 'sdk'],
        representativeQueries: [
          'which agent skills does Vocdoni publish',
          'is there an agent skill for the Vocdoni SDK',
          'how do I install the Vocdoni agent skills',
        ],
      },
      {
        identifier: urn('docs', 'developers'),
        displayName: 'Vocdoni developer documentation',
        type: 'text/html',
        url: `${host}/developers/docs`,
        description:
          'Integration guides for the Vocdoni API and SDK, covering authentication, censuses, election setup, ballot types, anonymous voting and results.',
        tags: ['documentation', 'sdk', 'integration'],
        representativeQueries: [
          'how do I integrate Vocdoni voting into my application',
          'what is the quickstart for the Vocdoni SDK',
          'how do I build a census for a Vocdoni election',
          'how does anonymous voting work in Vocdoni',
        ],
      },
      {
        identifier: urn('docs', 'developers-markdown'),
        displayName: 'Vocdoni developer documentation (markdown)',
        type: 'text/markdown',
        url: `${host}/${defaultLocale}/developers/docs.md`,
        description:
          'The same developer documentation served as raw markdown, so an agent can read it without parsing HTML. Every documentation page URL also answers to its `.md` equivalent.',
        tags: ['documentation', 'markdown', 'sdk'],
        representativeQueries: [
          'give me the Vocdoni developer docs as plain markdown',
          'fetch the Vocdoni documentation overview without HTML',
          'where are the raw markdown sources of the Vocdoni docs',
        ],
      },
      {
        identifier: urn('content', 'blog-feed'),
        displayName: 'Vocdoni blog feed',
        type: 'application/rss+xml',
        url: `${host}/blog/rss.xml`,
        description:
          'RSS feed of the Vocdoni blog: product announcements, protocol releases, governance and digital democracy write-ups.',
        tags: ['blog', 'rss', 'announcements'],
        representativeQueries: [
          'what has Vocdoni announced recently',
          'subscribe to the Vocdoni blog feed',
          'list the latest Vocdoni blog posts',
        ],
      },
      {
        identifier: urn('ops', 'status'),
        displayName: 'Vocdoni status page',
        type: 'text/html',
        url: DEVELOPERS_STATUS_URL,
        description: 'Live availability and incident history for the Vocdoni API and the services behind it.',
        tags: ['status', 'uptime', 'operations'],
        representativeQueries: [
          'is the Vocdoni API down',
          'what is the current uptime of Vocdoni services',
          'where is the Vocdoni status page',
        ],
      },
    ],
  }
}

export function buildAiCatalog(hostname: string, defaultLocale: string): string {
  return JSON.stringify(buildAiCatalogDocument(hostname, defaultLocale), null, 2) + '\n'
}

// --- plugin -----------------------------------------------------------------

/** Canonical ARD path first, predecessor second. Same bytes at both (see the header comment). */
export const ARD_OUTPUT_PATHS = ['.well-known/ard.json', '.well-known/ai-catalog.json']

export function ardPlugin(options: Options): Plugin {
  let clientOutDir: string
  let isSSRBuild = false
  let ran = false
  const host = stripSlash(options.hostname)

  return {
    name: 'ard-plugin',
    configResolved(config) {
      isSSRBuild = !!config.build.ssr
      const resolvedOutDir = config.build.outDir ? path.resolve(config.build.outDir) : path.resolve('dist')
      clientOutDir = resolvedOutDir.endsWith(`${path.sep}client`) ? resolvedOutDir : path.join(resolvedOutDir, 'client')
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url) return next()
        const url = req.url.split('?')[0]
        if (!ARD_OUTPUT_PATHS.includes(url.replace(/^\//, ''))) return next()

        res.setHeader('Content-Type', 'application/json; charset=utf-8')
        // Registries fetch this cross-origin from the browser, so it has to be readable by anyone.
        res.setHeader('Access-Control-Allow-Origin', '*')
        return void res.end(buildAiCatalog(host, options.defaultLocale))
      })
    },
    async closeBundle() {
      if (isSSRBuild) return
      if (ran) return
      ran = true

      const content = buildAiCatalog(host, options.defaultLocale)
      await Promise.all(
        ARD_OUTPUT_PATHS.map(async (rel) => {
          const out = path.join(clientOutDir, rel)
          await fs.mkdir(path.dirname(out), { recursive: true })
          await fs.writeFile(out, content, 'utf8')
        })
      )
    },
  }
}
