export const HARDCODED_COPY_BASELINE = new Set([
  'components/AlternativeHero.tsx|text|Vocdoni App',
  'components/Footer.tsx|attribute|GDPR',
  'components/HeroCards.tsx|text|0x7f...3a9c',
  'components/Navbar.tsx|attribute|Vocdoni App',
  'components/Navbar.tsx|text|App',
  'components/Navbar.tsx|text|Toggle menu',
  'components/TestimonialsSection.tsx|text|at',
  'components/features/IntegrationsPreview.tsx|expression|{ VocdoniSDK }',
  'components/features/IntegrationsPreview.tsx|text|VocdoniSDK()',
  'components/features/IntegrationsPreview.tsx|text|client =',
  'components/features/IntegrationsPreview.tsx|text|client.',
  'components/features/IntegrationsPreview.tsx|text|new',
  'components/features/IntegrationsPreview.tsx|text|npm',
  'components/features/ProjectsPreview.tsx|text|1.2M',
  'components/ui/carousel.tsx|text|Next slide',
  'components/ui/carousel.tsx|text|Previous slide',
  'components/ui/sheet.tsx|text|Close',
  'pages/+Layout.tsx|text|Continue',
  'pages/index/Counter.tsx|text|Counter',
])
